import Vue from 'vue'
import {
  Message,
  Button,
  Container,
  Header,
  Aside,
  Main,
  Footer,
  Row,
  Col,
  Menu,
  MenuItem,
  MenuItemGroup,
  Submenu,
  Tabs,
  TabPane,
  Card,
  Carousel,
  CarouselItem,
  Avatar,
  Link,
  Tag,
  Pagination,
  Image,
  Form,
  FormItem,
  Input,
  Divider,
  Breadcrumb,
  BreadcrumbItem,
  PageHeader,
  Table,
  TableColumn,
  Switch,
  Tooltip,
  Dialog,
  Select,
  Option,
  Badge,
  Popover,
  Backtop,
  Dropdown,
  DropdownMenu,
  DropdownItem,
  MessageBox
} from 'element-ui'

Vue.prototype.$message = Message
Vue.prototype.$confirm = MessageBox.confirm

Vue.use(Button)
Vue.use(Container)
Vue.use(Header)
Vue.use(Aside)
Vue.use(Main)
Vue.use(Footer)
Vue.use(Row)
Vue.use(Col)
Vue.use(Menu)
Vue.use(MenuItem)
Vue.use(MenuItemGroup)
Vue.use(Submenu)
Vue.use(Tabs)
Vue.use(TabPane)
Vue.use(Card)
Vue.use(Carousel)
Vue.use(CarouselItem)
Vue.use(Avatar)
Vue.use(Link)
Vue.use(Tag)
Vue.use(Pagination)
Vue.use(Image)
Vue.use(Form)
Vue.use(FormItem)
Vue.use(Input)
Vue.use(Divider)
Vue.use(Breadcrumb)
Vue.use(BreadcrumbItem)
Vue.use(PageHeader)
Vue.use(Table)
Vue.use(TableColumn)
Vue.use(Switch)
Vue.use(Tooltip)
Vue.use(Dialog)
Vue.use(Select)
Vue.use(Option)
Vue.use(Badge)
Vue.use(Popover)
Vue.use(Backtop)
Vue.use(Dropdown)
Vue.use(DropdownMenu)
Vue.use(DropdownItem)
